### ISSUE TITLE
getAlleles for X

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#12]
`getAlleles()` and `setAlleles()` are very useful new functions!
If two different alleles are given for a male on X, 
`setmarkers()` (and `addMarkers()`) silently (OK?!) chooses the first one 
but `getAlleles()`  returns both alleles:
``` r
library(pedtools)
x = nuclearPed(1)
m = marker(x, `1` = c(2,1), alleles = 1:2, name = "m",  chrom = "X")
x = setMarkers(x, m)
x
#>  id fid mid sex   m
#>   1   *   *   1   2
#>   2   *   *   2 -/-
#>   3   1   2   1   -
getAlleles(x)
#>   m.1 m.2
#> 1 "2" "1"
#> 2 NA  NA 
#> 3 NA  NA
```

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Actually, `setMarkers()` keeps both alleles (how else could they both appear in `getAlleles(x)`?). This is a feature rather than a bug. To detect (and remove) markers with male heterozygosity on X, you can use `mendelianCheck()`.

But the print method `print.ped()` indeed chooses the first allele. This is done to create a haploid output for markers on X. I agree this may be a source of confusion. Perhaps these "wrong" genotypes should be highlighted somehow when printed...with a star or something?

**Comment by thoree** [comment]
Thanks, I see: a star as you indicate would be fine.
